version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"

  rest-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
